### PR TITLE
Build with SvelteKit packager

### LINKED ISSUE #311: Add way to locally preview changes
Hi,
I'd like to preview changes made to the library locally - at first, I thought that I could just serve the docs and see any changes that way, but it turns out the docs always use the version from jsdelivr... Is there any way to use the local version?

### LINKED ISSUE #313: update package.json for vite5 / svelte 3
hello,

first, I'm happy to use this library.

But recently I faced an issue with `vite-plugin-svelte` and `vite5`
When this library was made, these components were older :-)

Here is the issue:
https://github.com/sveltejs/vite-plugin-svelte/issues/813

it seems svelte-fa is not following new recommended approach for svelte usage.

Running it now I can see
```
[vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-fa@3.0.4
Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

and here is the recommandation provided in the vite plugin svelte issue

> My recommendation would be to switch to svelte-package , add "type": "module", add an "exports" map , add publint to verify their package.json is ok. And last but not least maybe don't do mixed exports (default and named) from the index file. Thats not great.

I don't know if you would accept such PR ?

### PR DESCRIPTION
**Pull request by theodorejb**
* Components are now written in TypeScript, avoiding the need to maintain and test separate type definitions.
* Migrated docs site to use SvelteKit and Bootstrap 5 ([preview](https://theodorejb.github.io/svelte-fa/)).
* Switched from Prism to Highlight.js for code syntax highlighting.
* Enabled Prettier to autoformat code.
* Switched from Jest to Vitest for tests.
* Separate `gh-pages` branch is now used to deploy docs so autogenerated files don't have to be committed to master branch (this may require updating the GitHub Pages **Source** repository setting).
* Added contributing instructions file.

These changes should make it a lot easier to build and test the project, lowering the barrier for contributions and future maintenance.

Closes #313, closes #311

### CODE REVIEW

**Review by Walledgarden — APPROVED** [review]

**Comment by mcmxcdev** [comment]
Amazing work @theodorejb !

This PR would clean up lots of issues with this repo, @Cweili do you think you could find the time to review and get this merged? Would be highly appreciated :)

**Comment by Cweili** [comment]
@theodorejb Excellent work! I believe what we currently lack is some test cases to achieve complete coverage.

**Comment by theodorejb** [comment]
@Cweili Thanks! I don't believe coverage has actually decreased; it's that `.svelte` files were previously excluded from the report, and now they are not. So the coverage is simply more accurate now.

**Comment by Cweili** [comment]
Released with v4. Thanks!

**Pull request merged**
