### PR TITLE
Removing inline styles

### PR DESCRIPTION
**Pull request by marekdedic**
I've made it so no inline styles will be produced, *unless* you add a `<Fa style="...">` property - then you can't really be helped :D

Additionally, I've made it so the docs extract their CSS into a separate file, I mainly did it because I used the docs to test the thing (and you need CSS in `<head>` or a separate file to not trigger CSP), but it should improve performance, so I left it in the PR...

### CODE REVIEW

**Comment by Cweili** [comment]
Thanks!

**Comment by marekdedic** [comment]
Hi, sorry to bother, but could you please release this change? Thanks!

**Comment by Cweili** [comment]
@marekdedic I apologize for taking so long to reply to you.

I noticed that making this change would cause the package to lose one of its features, "No CSS file required."

Can we use a solution similar to ".style.background = 'red';" to solve the CSP issue?

**Comment by marekdedic** [comment]
Hi,
what do you mean by that? You can still use this package without a separate CSS file (CSP won't work for you then, but that's kind of the point of it :D). I re-configured the docs to extract the CSS [here](https://github.com/Cweili/svelte-fa/pull/308/files#diff-d9ac598525db39d1a50fde0797f79a016b14ccbe2c138ab2d1ffbc4a7e42dd6aR35), but the users don't have to do this (they can decide)...

**Comment by Cweili** [comment]
The solution similar to https://stackoverflow.com/a/57633533, whitch you mentioned in this reply, does not require extracting the CSS.
Extracting CSS files requires users to have additional build configurations to load these CSS files.

**Comment by marekdedic** [comment]
The current solution also doesn't require extracting the CSS - it's up to the user. If they want to keep the CSS as part of the JS, they can (they won't be able to have strict CSP, but that's kind of the point of strict CSP...).

**Comment by Cweili** [comment]
Sure, I think we can release this together with [this PR](https://github.com/Cweili/svelte-fa/pull/315). It will be a BREAKING CHANGE.

**Comment by Cweili** [comment]
Released with v4. Thanks!

**Pull request merged**
